// Shared symbol universe — single source of truth.
// Added Jul 22 2026: every page up to this point (dashboard search, sector
// map, OI Profile, OI Heatmap, OI History, EOD, Ask, Watchlist) maintains
// its own separate hardcoded copy of this list, which is exactly why it
// kept drifting out of sync (missing new symbols, delisted tickers left
// in). New pages should import from here instead of adding another copy.
// Existing pages can be migrated to this file in a future cleanup pass.

export const INDICES = ['NIFTY', 'BANKNIFTY', 'FINNIFTY']

export const STOCKS = [
  // Regenerated Sep 17 2026 from the confirmed-live backend F&O universe.
  '360ONE','AARTIIND','ABB','ABCAPITAL','ABFRL','ADANIENSOL','ADANIENT','ADANIGREEN',
  'ADANIPORTS','ADANIPOWER','ALKEM','AMBUJACEM','ANGELONE','APOLLOHOSP','APOLLOTYRE',
  'ASHOKLEY','ASIANPAINT','ASTRAL','ATHERENERG','AUBANK','AUROPHARMA','AXISBANK',
  'BAJAJ-AUTO','BAJAJFINSV','BAJFINANCE','BALKRISIND','BANDHANBNK','BANKBARODA',
  'BANKINDIA','BDL','BEL','BHARATFORG','BHARTIARTL','BHEL','BIOCON','BOSCHLTD','BPCL',
  'BRITANNIA','BSE','CAMS','CANBK','CANFINHOME','CDSL','CHOLAFIN','CIPLA','COALINDIA',
  'COFORGE','CONCOR','COROMANDEL','CROMPTON','DABUR','DALBHARAT','DEEPAKNTR','DELHIVERY',
  'DIVISLAB','DIXON','DLF','DRREDDY','EICHERMOT','ETERNAL','EXIDEIND','FEDERALBNK',
  'FORCEMOT','FORTIS','GAIL','GLENMARK','GMRAIRPORT','GNFC','GODFRYPHLP','GODREJCP',
  'GODREJPROP','GRANULES','GRASIM','GUJGASLTD','GVT&D','HAL','HAVELLS','HCLTECH',
  'HDFCAMC','HDFCBANK','HDFCLIFE','HEROMOTOCO','HINDALCO','HINDCOPPER','HINDPETRO',
  'HINDUNILVR','HINDZINC','HUDCO','HYUNDAI','ICICIBANK','ICICIGI','ICICIPRULI','IDEA',
  'IDFCFIRSTB','IEX','IGL','INDIGO','INDUSINDBK','INDUSTOWER','INFY','IOC','IPCALAB',
  'IREDA','IRFC','ITC','JINDALSTEL','JIOFIN','JKCEMENT','JSWENERGY','JSWSTEEL',
  'KALYANKJIL','KAYNES','KEI','KFINTECH','KOTAKBANK','KPITTECH','LAURUSLABS','LICHSGFIN',
  'LICI','LODHA','LT','LTF','LTM','LTTS','LUPIN','M&M','MANAPPURAM','MANKIND','MARICO',
  'MARUTI','MAZDOCK','MCX','MFSL','MGL','MOTHERSON','MPHASIS','MUTHOOTFIN','NAM-INDIA',
  'NATIONALUM','NAVINFLUOR','NBCC','NESTLEIND','NHPC','NLCINDIA','NMDC','NTPC','NYKAA',
  'OIL','ONGC','PATANJALI','PAYTM','PERSISTENT','PETRONET','PFC','PGEL','PIDILITIND',
  'PIIND','PNB','PNBHOUSING','POLYCAB','POWERGRID','POWERINDIA','PREMIERENE','PVRINOX',
  'RAMCOCEM','RAYMONDLSL','RBLBANK','RECLTD','RELIANCE','RRKABEL','RVNL','SAGILITY',
  'SAIL','SBICARD','SBILIFE','SBIN','SHRIRAMFIN','SIEMENS','SOLARINDS','SRF','SUNPHARMA',
  'SUZLON','SWIGGY','TATACONSUM','TATAELXSI','TATAPOWER','TATASTEEL','TCS','TECHM',
  'TITAN','TMPV','TORNTPHARM','TORNTPOWER','TRENT','TVSMOTOR','ULTRACEMCO','UNIONBANK',
  'UNOMINDA','UPL','VBL','VEDL','VMM','VOLTAS','WAAREEENER','WIPRO','YESBANK','ZYDUSLIFE',
].sort()

export const ALL_SYMBOLS = [...INDICES, ...STOCKS]
